### ISSUE TITLE
Present a signing screen for an envelope by Id.

### ISSUE THREAD

**Issue by rpelorosso** [docusign/iOS-offline-templates-sdk#12]
Hi!

My application needs to present the signing screen for an envelope, but the envelope should not be created in the app, but in a server. This server provides the app with the envelope id. 

I couldn't find anything in the documentation about displaying the signing form for an envelope by id. 

Is it possible to do so?

Thank you!
Rodrigo

**Comment by ashokds** [comment]
Hi @rpelorosso ,

As of the current version, it's not possible to present an online signing session with SDK when the envelope doesn't originate in the SDK. 

Thanks.

**Comment by rpelorosso** [comment]
I thought that would be the case, 

I guess we'll just create a signing link and display it using a webview. 

Thanks!
Rodrigo

**Comment by JeevanEashwar** [comment]
> Hi @rpelorosso ,
> 
> As of the current version, it's not possible to present an online signing session with SDK when the envelope doesn't originate in the SDK.
> 
> Thanks.

Hi DocuSign Dev team,
I want to present a signing screen for an envelope by Id. Is this feature available in any versions now?

**Comment by JeevanEashwar** [comment]
For the envelopes generated online, I get this user message from the SDK
`Envelope is ready for sync and can not be resumed for signing.`

**Comment by thomas-dang** [comment]
Hi @JeevanEashwar,

The ability to use our SDK to open the online signing ceremony for an envelope that already exists on the server is not currently available, but it is something on our roadmap.

Thanks.

**Comment by augustocollerone** [comment]
Hi @thomas-dang, 

Just wanted to check if this feature is already implemented since when I try to open an envelope ID that was created on the server I get an empty full screen view controller on the iOS SDK.

Thanks

**Comment by ashokds** [comment]
Hi @augustocollerone ,

Yes, this feature is publically available.

Have you registered for the notifications (`DSMSigningCancelledNotification` & `DSMSigningCompletedNotification`) that gives more information if *Online Signing* exits because of any errors, say authentication failure or if the logged-in user doesn't have access to the envelope. Please note that for Captive/Embedded signing envelopes, the sender account and the logged-in user have to be the same. 

An examples of error returned with `DSMSigningCancelledNotification`:
- "Envelope (envelopeId: "1a94fe5b-0d7c-4485-b833-d15a3c726083") has invalid captive recipients associated with clientUserId: "1".


More details:

```
/*!
 * @brief Notification sent when envelope signing is completed in online or offline mode by all current signers.
 * @discussion Returned userInfo contains signingMode associated with DSMSigningModeKey and templateId associated with DSMTemplateIdkey. Returned userInfo also contains envelopeId associated with DSMEnvelopeIdKey only when online signing; during offline signing, envelopeId for signed envelope is sent with DSMEnvelopeCachedNotification.
 * Conforming to DSMEnvelopesManagerOfflineSigningDelegate allows client apps to receive callback events associated with recipient selection or individual recipient events for start and finish offline signing.
 * This can be posted on a thread other than MainThread.
 * [[NSNotificationCenter defaultCenter] postNotificationName:DSMSigningCompletedNotification object:viewController userInfo:userInfo];
 * @see DSMEnvelopesManager.h
 * @see DSMEnvelopesManagerOfflineSigningDelegate
 */
extern NSString * const DSMSigningCompletedNotification;

/*!
 * @brief Notification sent when signing is cancelled upon error or dismissed based on user-actions.
 * User actions which may trigger this notifications during Online or Offline Signing are:
 * - Exit Offline Signing by saving or discarding the envelope currently being signed
 * - Exit Online Signing by cancelling or choosing to 'Sign Later' the envelope
 * @discussion Returned userInfo has envelopeId associated with DSMEnvelopeIdKey. This can be posted on a thread other than MainThread.
 * [[NSNotificationCenter defaultCenter] postNotificationName:DSMSigningCancelledNotification object:viewController userInfo:userInfo];
 */
extern NSString * const DSMSigningCancelledNotification;
```

Thanks

**Comment by augustocollerone** [comment]
Hi @ashokds. Thank you for your response,

### My implementation of the DocuSign SDK: 
```
        self.mDSMEnvelopesManager?.presentSigning(withPresenting: presentingController, envelopeId: envelopeId, animated: true, completion: { (_, error) in
            if let error = error {
                print("DS Error: ", error)
            }
        })
```

The envelope ID is provided by the server, I'm not getting any errors on this method completion handler nor on the before mentioned notifications. Is there any other method on the DocuSign SDK that I should be using to accomplish the desired flow?

### This is the result I'm getting:
![IMG_0147](https://user-images.githubusercontent.com/23138661/94854249-0168f200-0403-11eb-8d49-d11dd87144be.PNG)

Thank you

**Comment by ashokds** [comment]
Hi @augustocollerone ,

Most of the errors & success related information is reported back with the following notifications: 

- `DSMSigningCancelledNotification`
- `DSMSigningCompletedNotification`

Details in above comment.

Also, need to register for these notifications with the object that remains active in the background while the SDK components are active. So if the listening viewControllers is deallocated while the signing is in progress, client-app would miss these errors.

Thank you.

**Comment by KrishnaKishore1992** [comment]
Team we still have this issue. When trying to open envelope that is created by server by using below function Docusign viewcontroller is presented and dismissed immediately.

self.mDSMEnvelopesManager?.presentSigning(withPresenting: presentingController, envelopeId: envelopeId, animated: true, completion: { (_, error) in
            if let error = error {
                print("DS Error: ", error)
            }
        })

When I added notification observers, DSMSigningCompletedNotification is called and says that document is signed. Actually that document is not signed.

name = DSMSigningCompletedNotification, object = Optional(<DSMSigningViewController: 0x10718d800>), userInfo = Optional([AnyHashable("signingMode"): online, AnyHashable("envelopeId"): 992ca18c-c3ad-41f8-b9e7-18b9a0981bd0])
