### ISSUE TITLE
Getting -[NSBundle initWithURL:]: nil URL argument when using "presentSendTemplateControllerWithTemplate"

### ISSUE THREAD

**Issue by freemadc2** [docusign/iOS-offline-templates-sdk#2]
Hi,

I am getting an crash
 instantly when I use the method "presentSendTemplateControllerWithTemplate". The error relates to "-[NSBundle initWithURL:]: nil URL argument". I am not sure why. I am passing a correct templateID. My code is below. If you could lease help me with this. Thanks.

        DSMManager.login(withUserId: DocuSignHelper.userName,
                         password: DocuSignHelper.password,
                         integratorKey: DocuSignHelper.integratorKey,
                         host: URL.init(string: DocuSignHelper.host)!,
                         completionBlock:  { (error) in
            DSMTemplatesManager().presentSendTemplateControllerWithTemplate(withId: templateID, signingMode: .online, presenting: view, animated: true, completion: { (uvc, error) in
                let stringString = ""
            })
        })

Exception:
![screen shot 2017-10-08 at 8 15 51 pm](https://user-images.githubusercontent.com/10815857/31324248-bd65ab68-ac65-11e7-86e9-cff3213cefa7.png)

**Comment by ashokds** [comment]
Hi @freemadc2,

Please add details of your setup: CocoaPods, Swift & Xcode version.
Thanks for reporting this with sample code & call stack.

**Comment by freemadc2** [comment]
Ah @ashokds,

This was the issue. Thank you very much.

**Comment by HarRes123** [comment]
I'm getting this issue as well, and the solution you provided did not work.

**Comment by HarRes123** [comment]
@mmohareb https://github.com/docusign/native-ios-sdk/issues/148
