### ISSUE TITLE
embedded signing view?

### ISSUE THREAD

**Issue by dktan** [docusign/iOS-offline-templates-sdk#3]
As I read through the docs, there is no functionality of embedded signing, only native view this lib provide is a template controller view for sending templates to customers. 

But, as your advertised here: https://docs.docusign.com/ios_sdk/index.html, there should be a view that can collect signatures from customers, which is kinda of embedded signing.

If you do have this embedded signing feature, please tell me where to find it.
If you do not, I will try find work around myself.

**Comment by iOSSDK-DocuSign** [comment]
It supports Online and Offline Signing with - Embedded signing view.

**Comment by dktan** [comment]
@iOSSDK-DocuSign 
![image](https://user-images.githubusercontent.com/12505414/34175101-1a86c99e-e4b0-11e7-9702-4210a06689dc.png)

**Comment by dktan** [comment]
@iOSSDK-DocuSign  I do find embeddedRecipientStartURL function in DSMRecipient, but this returns a url, not a ios view

**Comment by iOSSDK-DocuSign** [comment]
They are the two options to present signing view controller. presentSendTemplateControllerWithTemplateWithId   presents the signing view controller on passed in presentingController.

**Comment by dktan** [comment]
@iOSSDK-DocuSign 
![image](https://user-images.githubusercontent.com/12505414/34180097-46297c60-e4c2-11e7-809b-98f5b2bba6bd.png)
I got this view, seems like I can send a template through this view, not sign

**Comment by iOSSDK-DocuSign** [comment]
If you have a template with a placeholder for signer and when logged in user is added to it on this screen, or in-person signer with logged in user as host will trigger signing. As logged in user is one of the signer or a host...

**Comment by dktan** [comment]
So, this lib can not provide a view like the web page /v2/accounts/{accountId}/envelopes/{envelopeId}/views/recipient provides for customer? right?

**Comment by iOSSDK-DocuSign** [comment]
It provides signing ceremony for a user but it's not a webpage but UI component which is internally loading the same Web page. but does not provide web page.

**Comment by dktan** [comment]
I mean a UIView, like that web page, where a end user who don't have docusign account can just sign a document.

**Comment by iOSSDK-DocuSign** [comment]
If the user is not on DocuSign then someone needs to host it for that user and then they can sign. but this SDK does not give a UIVew for them. You can use other API to do that.

**Comment by iOSSDK-DocuSign** [comment]
@dktan  I am closing the issue as there are no further questions please feel free to open up the new issue if you have an issue. will be happy to help you.

**Comment by patelvivek9115** [comment]
I am getting same issue I just want to open signing view that user can sign the document and save it I am not able to find any api in sdk I tried with method presentEditRecipientsControllerForEnvelope by passing envelope id but nothing is happening

**Comment by patelvivek9115** [comment]
@dktan  did you find any way to open the signing view that user can able to sign the document, please share your views thanks.
