### ISSUE TITLE
Linker command failed with exit code 1

### ISSUE THREAD

**Issue by vijaypalve** [docusign/iOS-offline-templates-sdk#6]
I have downloaded "iOS-offline-templates-sdk" and tried to run the sample project (docusign-sdk-sample-objc) but it throws "Linker command failed with exit code 1" error.

I am using Xcode 9.3 and MAC OS 10.13.3

I have performed all the steps mentioned on the sample app page ref.-https://docs.docusign.com/ios_sdk/developer.html.

I have also performed following steps to resolve the issue -
1. installed pod using -> "pod install"
2. remove pod file and podfile.lock file and update pod using -> "rm -rf Pods/ Podfile.lock ;"

But the error was not resolved.

Please find the attached screen shots....
![screen shot 2018-06-05 at 4 52 21 pm](https://user-images.githubusercontent.com/14092016/40977491-bf699fb4-68ee-11e8-842a-61f15434c30e.png)
![screen shot 2018-06-05 at 4 51 45 pm](https://user-images.githubusercontent.com/14092016/40977492-bf9e510a-68ee-11e8-98eb-972fd484b0f3.png)

Please tell me what more I can do to get it working.

**Comment by iOSSDK-DocuSign** [comment]
Can you check if **DocusignSDK.bundle** is added to sample App. when adding the framework to Embeded Binaries,  don't delete the references instead add the SDK directly to Embedded Binaries.
Once Bundle and framework appears in project navigator, you may delete the old references.

Inaddition to this, we would recommend **CocoaPods version ~ 1.1.1** . Updating the pods may also leads to linker issues.

If issue persists can you please attach the screenshots of Project Navigator, Copy Bundle resources and CocoaPods Version that will help us analyze the issue further.

**Comment by iOSSDK-DocuSign** [comment]
@vijaypalve - Helpful commands to verify the cocoapods version & remove/install specific versions.

// verify the version
`pod --version`

// remove higher versions than 1.1.1
`sudo gem uninstall cocoapods`

// install specific version
`sudo gem install cocoapods -v 1.1.1`

link: https://stackoverflow.com/questions/20487849/how-to-downgrade-or-install-an-older-version-of-cocoapods

**Comment by vijaypalve** [comment]
Thank you @iOSSDK-DocuSign 
I have verified the cocoapods version & remove/install specific versions 1.1.1.

But the error was not resolved.
I have attached screen shots of "project navigator" and "Build Setting"
![screen shot 2018-06-06 at 10 19 29 am](https://user-images.githubusercontent.com/14092016/41017724-d8a818fe-6973-11e8-8694-5f1c61c0acdf.png)
![screen shot 2018-06-06 at 10 19 50 am](https://user-images.githubusercontent.com/14092016/41017725-d8dddc82-6973-11e8-9345-700c6ee76d1f.png)
![screen shot 2018-06-06 at 10 20 09 am](https://user-images.githubusercontent.com/14092016/41017726-d9108b5a-6973-11e8-9d37-cdb7d32848b4.png)

**Comment by vijaypalve** [comment]
![screen shot 2018-06-06 at 10 29 14 am](https://user-images.githubusercontent.com/14092016/41017862-9bf2fdd8-6974-11e8-90ce-07ae2fbeee2b.png)

**Comment by ashokds** [comment]
@vijaypalve, Please use `docusign-sdk-sample-objc.xcworkspace` instead of `docusign-sdk-sample-objc.xcodeproj`. That should resolve it.

**Comment by vijaypalve** [comment]
@iOSSDK-DocuSign Thank you it works .

I need to implement a user to make sign in my app using DocuSign. I have implemented Android and iOS application using Xamarin.Forms. How to implement Docusign in Xamarin.Forms?

**Comment by iOSSDK-DocuSign** [comment]
Hi Vijay,

We have not tested implementation of our sdk in Xamarin.Forms, we don’t have that expertise as well. Try it out and let us know, if you run into any native (Obj-C or Swift) implementation issue we can be of more help.

Best, -Kiran


_____________________________

**Comment by iOSSDK-DocuSign** [comment]
Closing this issue as resolved.
